### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by CarolineInfo** [tlth/web#194]
![framsida ny](https://user-images.githubusercontent.com/25298143/30317534-a59083de-97aa-11e7-9ab7-4883e18d2044.jpg)

This is what I would like the new page to look like :)

**Comment by davidwessman** [comment]
If you add multiple images on https://tlth.se/settings they will rotate :) 
But the logo is always there atm.

**Comment by richardluong** [comment]
Hannah and I started on some rework on the hannah-smaller-design branch.
I’ll try to finish it this week.
tis 12 sep. 2017 kl. 11:15 skrev David Wessman <notifications@github.com>:
