### ISSUE TITLE
Available positions

### ISSUE THREAD

**Issue by CarolineInfo** [tlth/web#196]
Okay so this will be a long issue, but hopefully you will understand what I want ^^

So basically I would like you to copy this page http://www.lundaekonomerna.se/positions/
![untitled-1](https://user-images.githubusercontent.com/25298143/30327011-d458fe7e-97ca-11e7-8dc1-b286c94b4224.jpg)

I want a two tables divided between positions of trust and committee positions. The tables shows name of the positions, which committee, how long the mandate lasts.
When you press on a row in the table it will extend and show a longer description, contact person and a box where it says "candidate or nominate here". When you press that box your are directed to a new window with the form.

It would be great if I could add new positions in a similar way we do for meetings and documents
![lagg till](https://user-images.githubusercontent.com/25298143/30318599-deed2e86-97ad-11e7-8ec7-4676bf1e9a24.jpg)

## There I should be able to fill in:
- If it's a position of trust or committee position (preferable with a drop down menu)
- Name of the position
- Which committee it belongs to 
- How long your mandate lasts
- Description of the position
- A box where you can put a google form link 
- Contact person (a drop down menu similar to the one I use when I select contact person for a page)

I don't know how hard this task is but it would be great if it's done before December!

**Comment by richardluong** [comment]
@CarolineInfo please try tlth.se/positions out and tell us if there's something missing. Otherwise we can close this issue.

**Comment by CarolineInfo** [comment]
Almost perfect, but can you add an option where you can choose if the position is a _position of trust_ or a _committee position_? This would generate two tables like this page https://tlth.se/lediga
