### ISSUE TITLE
New picture for the board

### ISSUE THREAD

**Issue by CarolineInfo** [tlth/web#200]
If someone could change the picture for this page https://tlth.se/board, that would be great :)

**Comment by hannushka** [comment]
Change it to what picture? :)

**Comment by CarolineInfo** [comment]
Whops, forgot to attach the picture...
![hemsidan](https://user-images.githubusercontent.com/25298143/32487647-91b64bf6-c3aa-11e7-8e78-ff7743ab83ac.jpg)

**Comment by hannushka** [comment]
Okej! Vilka namn ska det stå under? Idag är där 5 namn men där är ju 8 personer på bilden :)

**Comment by CarolineInfo** [comment]
- Oscar Rundbäck Martinsson (Styrelseledamot)
- Carl Kardell (Styrelseledamot)
- Victor Sandberg (Styrelseledamot)
